server:
  port: 8200
spring:
  application:
    name: testFeign
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000